//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::genres::Entity as Genres;
pub use super::items::Entity as Items;
pub use super::locations::Entity as Locations;
pub use super::passkeys::Entity as Passkeys;
pub use super::users::Entity as Users;
